FROM python:3.10.11-slim

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_NO_CACHE_DIR=1

WORKDIR /app

COPY employee/requirements.txt ./requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY employee/ ./
EXPOSE 5001

CMD ["gunicorn", "-b", "0.0.0.0:5001", "--access-logfile", "-", "app:create_app()"]