apiVersion: v1
kind: ConfigMap
metadata:
  name: iep-config
  namespace: iep
data:
  DIRECTOR_ROLE: "director"
  EMPLOYEE_ROLE: "employee"
  MONGO_URL: "mongodb://mongo:27017"
  REDIS_URL: "redis://redis:6379/0"
  GANACHE_RUL: "http://ganache:8545"
  VOTING_DEADLINE_SECONDS: "3600"
  MYSQL_DATABASE : "iep_auth"
