apiVersion: v1
kind: Secret
metadata:
  name: iep-secret
  namespace: iep
type: Opaque
stringData:
  JWT_SECRET_KEY: "IEP_TAJNA"
  SQL_DATABASE_URL: "mysql+pymysql://root:ieppw@mysql:3306/iep_auth?charset=utf8mb4"
  MYSQL_ROOT_PASSWORD: "ieppw"
  DIRECTOR_EMAIL: "onlymoney@gmail.com"
  DIRECTOR_FORENAME: "Scrooge"
  DIRECTOR_SURNAME: "McDuck"
  DIRECTOR_PASSWORD: "evenmoremoney"