apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  namespace: iep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data
  namespace: iep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: iep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ganache-data
  namespace: iep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
