{{/* helm uninstall deletes these PVCs and the data with them. */}}
{{- range $item := list "mysql" "mongo" "redis" }}
{{- with index $.Values.infra $item }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $item }}-data
  labels:
    app.kubernetes.io/name: {{ $item }}-data
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: iep
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .storageClass }}
  storageClassName: {{ .storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .storage | quote }}
{{- end }}
{{- end }}
